version: '3'
services:
  web: 
    image: nginx:1.11-alpine
    volumes:
      - ${CODE_DIR}:/code
      - ./env/config/site.conf:/etc/nginx/conf.d/site.conf
      - ./env/cert:/certs
    ports:
      - "8888:80"
      - "80:80"
      - "433:433"
  php:
    build: ./env/php8
    volumes: 
      - ${CODE_DIR}:/code
      # - ./env/supervisor/conf.d:/etc/supervisor/conf.d
      - ./env/entrypoint:/entrypoint
      - ./env/php8/cron:/etc/cron.d/engaz-cron
      - ./env/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    entrypoint: /entrypoint/entrypoint.sh
    environment:
      XDEBUG_CONFIG: client_host=${HOST_IP} client_port=9000
      XDEBUG_MODE: debug
      XDEBUG_TRIGGER: 
    extra_hosts:
      - "api.sb.dev:${HOST_IP}"
      - "sbm.me:${HOST_IP}"
      - "sb.me:${HOST_IP}"
  redis:
    image: redis:3.2
    volumes:
      - ./env/redis_data:/data
  mongo:
    image: mongo
    volumes:
      - ./env/mongo:/etc/mongo 
    ports:
      - "27017:27017"
    # command: --config /etc/mongo/mongod.conf
  database:
    image: mysql:8.0
    volumes:
      - ./env/mysql_data:/var/lib/mysql
      - ./env/backup.sql:/backup.sql
      - ./env/mysql_config:/etc/mysql/conf.d
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
      